# Use the official JupyterLab image as a parent image
FROM jupyter/base-notebook:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Install dependencies
COPY devops/requirements.txt ./
USER root
RUN pip install --no-cache-dir -r requirements.txt && rm requirements.txt

# Copy code, notebooks, and data into the container
COPY code ./code
COPY notebooks ./notebooks
COPY data ./data

# Switch back to the non-root user for Jupyter
USER jovyan

# Start command
CMD ["start.sh", "jupyter", "lab", "--LabApp.token=''", "--ip='0.0.0.0'", "--port=8888", "--allow-root"]
